CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(60) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	is_verified BOOLEAN DEFAULT FALSE,
	role VARCHAR(20) NOT NULL DEFAULT 'user',
	created_at TIMESTAMPTZ DEFAULT NOW(),
	updated_at TIMESTAMPTZ DEFAULT NOW()
);